[project]
name = "commit-maker"
version = "0.3.0"
authors = [
  { name="Alex Bulgakov", email="sashayerty@ya.ru" },
]
description = "CLI utility that generates commit messages using AI"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.8"
dependencies = [
    "requests>=2.32.3",
    "rich-argparse>=1.7.0",
]

[project.scripts]
commit_maker = "commit_maker.main:main"

[project.urls]
homepage = "https://github.com/sashayerty/commit_maker"
github = "https://github.com/sashayerty/commit_maker"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}
